# Generated by Django 5.2.9 on 2025-12-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCurrency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.IntegerField(default=1, help_text='Lower value means higher priority.')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='provider',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together={('source_currency', 'exchanged_currency', 'valuation_date', 'provider')},
        ),
    ]
