# Generated by Django 5.2.9 on 2025-12-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCurrency', '0002_provider_alter_currencyexchangerate_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConverterProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Currency Converter',
                'verbose_name_plural': 'Currency Converters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MyCurrency.currency',),
        ),
    ]
