# Generated by Django 5.2.9 on 2025-12-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyCurrency', '0003_currencyconverterproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyConverterProxy',
        ),
    ]
